// ── DATA ──────────────────────────────────────────────────────────────────
const STATIONS = [
  { id:"JM01", name:"Mansarovar",          nameHi:"मानसरोवर",         zone:1, timeToNext:120, isTerminus:true  },
  { id:"JM02", name:"New Aatish Market",   nameHi:"न्यू आतिश मार्केट", zone:1, timeToNext:110 },
  { id:"JM03", name:"Vivek Vihar",         nameHi:"विवेक विहार",        zone:1, timeToNext:105 },
  { id:"JM04", name:"Shyam Nagar",         nameHi:"श्याम नगर",          zone:1, timeToNext:115 },
  { id:"JM05", name:"Ram Nagar Ghat Gate", nameHi:"राम नगर घाट गेट",   zone:2, timeToNext:120 },
  { id:"JM06", name:"Civil Lines",         nameHi:"सिविल लाइंस",        zone:2, timeToNext:130, isTourist:true },
  { id:"JM07", name:"Railway Station",     nameHi:"रेलवे स्टेशन",       zone:2, timeToNext:140, isInterchange:true, isTourist:true },
  { id:"JM08", name:"Sindhi Camp",         nameHi:"सिंधी कैंप",          zone:2, timeToNext:125 },
  { id:"JM09", name:"Chandpole",           nameHi:"चांदपोल",             zone:3, timeToNext:115, isTourist:true },
  { id:"JM10", name:"Chhoti Chaupar",      nameHi:"छोटी चौपड़",          zone:3, timeToNext:100, isTourist:true },
  { id:"JM11", name:"Badi Chaupar",        nameHi:"बड़ी चौपड़",           zone:3, timeToNext:0,   isTerminus:true, isTourist:true },
];

const FARE = {
  "1-1":10, "1-2":15, "1-3":20,
  "2-1":15, "2-2":10, "2-3":15,
  "3-1":20, "3-2":15, "3-3":10
};

const ATTRACTIONS = {
  JM06:[
    { name:"Birla Mandir",    nameHi:"बिड़ला मंदिर",  exit:"Exit 2", walk:"15 min", fee:"Free", tip:"Visit after sunset — white marble glows against the dark sky.", category:"Temple"  },
    { name:"Albert Hall",     nameHi:"अल्बर्ट हॉल",   exit:"Exit 1", walk:"18 min", fee:"₹40",  tip:"Egyptian mummy in basement — most visitors miss it entirely.",  category:"Museum"  },
  ],
  JM07:[
    { name:"Railway Station", nameHi:"रेलवे स्टेशन",  exit:"Exit 1", walk:"2 min",  fee:"Free", tip:"Heritage architecture — photograph the facade from the main road.", category:"Heritage"},
  ],
  JM09:[
    { name:"Chandpole Bazaar",nameHi:"चांदपोल बाज़ार", exit:"Exit 1", walk:"1 min",  fee:"Free", tip:"Best for blue pottery. Bargain to 60% of asking price.",         category:"Shopping"},
    { name:"Old City Walk",   nameHi:"पुराना शहर",     exit:"Exit 2", walk:"0 min",  fee:"Free", tip:"7 AM walk — chai wallahs, temple bells, pink walls at dawn.",    category:"Walk"    },
  ],
  JM10:[
    { name:"Tripolia Bazaar", nameHi:"त्रिपोलिया बाज़ार",exit:"Exit 1",walk:"3 min", fee:"Free", tip:"Lac bangles ₹20 a set. Traditional Rajasthani jewellery hub.",    category:"Shopping"},
  ],
  JM11:[
    { name:"Hawa Mahal",      nameHi:"हवा महल",        exit:"Exit 2", walk:"4 min",  fee:"₹50",  tip:"Go inside — most tourists only photograph the facade.",           category:"Heritage"},
    { name:"City Palace",     nameHi:"सिटी पैलेस",     exit:"Exit 1", walk:"8 min",  fee:"₹200", tip:"Mubarak Mahal has Maharaja's weapons — most tourists rush past.", category:"Heritage"},
    { name:"Jantar Mantar",   nameHi:"जंतर मंतर",      exit:"Exit 1", walk:"10 min", fee:"₹50",  tip:"Samrat Yantra tells time to 2 seconds — stand in its shadow.",   category:"UNESCO"  },
    { name:"Johari Bazaar",   nameHi:"जौहरी बाज़ार",   exit:"Exit 2", walk:"2 min",  fee:"Free", tip:"Bargain to 50% of asking price — it is expected here.",           category:"Shopping"},
  ],
};

const EXITS = {
  JM06:["Exit 1 → Civil Lines, High Court","Exit 2 → Statue Circle, Birla Mandir"],
  JM07:["Exit 1 → Railway Station Main","Exit 2 → Bus Stand, Prepaid Auto","Exit 3 → Sindhi Camp, Hotels"],
  JM09:["Exit 1 → Chandpole Bazaar","Exit 2 → Old City Heritage Walk"],
  JM10:["Exit 1 → Tripolia Bazaar, Chhoti Chaupar","Exit 2 → Old City Lanes"],
  JM11:["Exit 1 → City Palace, Jantar Mantar","Exit 2 → Hawa Mahal, Johari Bazaar"],
};

const T = {
  EN: {
    route:"Route", explore:"Explore", stations:"Stations", safety:"Safety",
    from:"From — Starting Station", to:"To — Destination Station",
    search:"Search station...", back:"Back",
    endJourney:"End Journey", simulated:"Simulated · Not live",
    planJourney:"Plan Your Journey",
    eyebrow:"Pink Line · 11 Stations · Mansarovar ↔ Badi Chaupar",
    popularTourists:"POPULAR WITH TOURISTS",
    selectHint:"Select stations above to see the fastest route",
    startJourney:"Start Live Journey",
    estimated:"Estimated times · Not an official JMRC app",
    stops:"stops", est:"est.", token:"token", smartCard:"smart card",
    currentStation:"CURRENT STATION", nextStation:"NEXT STATION (est.)",
    minRemaining:"minutes remaining",
    allStops:"ALL STOPS",
    arrived:"You have arrived!",
    exitGuidance:"EXIT GUIDANCE",
    planNew:"Plan New Route",
    back2:"Back", touristStation:"TOURIST STATION",
    metroInfo:"METRO INFO",
    first:"First", last:"Last", freq:"Freq",
    exitGuide:"EXIT GUIDE",
    nearbyAtts:"NEARBY ATTRACTIONS",
    fromHere:"From Here", toHere:"To Here",
    exploreTitle:"Explore Jaipur",
    exploreSub:"Tourist spots reachable by metro",
    touristStations:"TOURIST STATIONS",
    allStations:"All Stations",
    stationsSub:"Pink Line · Mansarovar ↔ Badi Chaupar",
    safetyTitle:"Safety & Help",
    safetySub:"Emergency contacts and travel tips",
    emergencyContacts:"EMERGENCY CONTACTS",
    travelTips:"TRAVEL TIPS",
    disclaimer:"Unofficial app · Not affiliated with JMRC\nAll timings & fares are estimates · Verify at station",
    towardsBC:"Towards Badi Chaupar",
    towardsMans:"Towards Mansarovar",
    spots:"spots",
    walk:"walk",
    nearestTitle:'Find Nearest Station',
    nearestSub:'Use GPS · Walking directions',
  },
  HI: {
    route:"रूट", explore:"एक्सप्लोर", stations:"स्टेशन", safety:"सुरक्षा",
    from:"यहाँ से — कहाँ से?", to:"यहाँ तक — कहाँ जाना है?",
    search:"स्टेशन खोजें...", back:"वापस",
    endJourney:"यात्रा समाप्त करें", simulated:"अनुमानित • लाइव नहीं",
    planJourney:"अपनी यात्रा प्लान करें",
    eyebrow:"पिंक लाइन · 11 स्टेशन",
    popularTourists:"पर्यटन स्थल",
    selectHint:"स्टेशन चुनें और सबसे तेज़ रूट देखें",
    startJourney:"यात्रा शुरू करें",
    estimated:"अनुमानित समय · JMRC की आधिकारिक ऐप नहीं",
    stops:"स्टेशन", est:"अनुमानित", token:"टोकन", smartCard:"स्मार्ट कार्ड",
    currentStation:"अभी", nextStation:"अगला स्टेशन (अनुमानित)",
    minRemaining:"मिनट में पहुँचेंगे",
    allStops:"सभी स्टॉप",
    arrived:"आप पहुँच गए!",
    exitGuidance:"निकास मार्गदर्शन",
    planNew:"नई यात्रा प्लान करें",
    back2:"वापस", touristStation:"TOURIST STATION",
    metroInfo:"मेट्रो जानकारी",
    first:"पहली", last:"आखिरी", freq:"फ्रीक्वेंसी",
    exitGuide:"निकास मार्गदर्शन",
    nearbyAtts:"पास के आकर्षण",
    fromHere:"यहाँ से", toHere:"यहाँ तक",
    exploreTitle:"जयपुर खोजें",
    exploreSub:"मेट्रो से पर्यटन स्थल",
    touristStations:"पर्यटन स्टेशन",
    allStations:"सभी स्टेशन",
    stationsSub:"पिंक लाइन · मानसरोवर ↔ बड़ी चौपड़",
    safetyTitle:"सुरक्षा और सहायता",
    safetySub:"आपातकालीन नंबर और सुझाव",
    emergencyContacts:"आपातकालीन नंबर",
    travelTips:"सुरक्षा सुझाव",
    disclaimer:"यह JMRC की आधिकारिक ऐप नहीं है\nसभी समय और किराए अनुमानित हैं",
    towardsBC:"बड़ी चौपड़ की ओर",
    towardsMans:"मानसरोवर की ओर",
    spots:"स्थान",
    walk:'पैदल',
    nearestTitle:'नज़दीकी स्टेशन खोजें',
    nearestSub:'GPS से खोजें · दिशा निर्देश',
  }
};
